# Use root/example as user/password credentials
version: '3.1'

services:
  mazadataapp:
    volumes:
      - .:/mazadatemasr
    build:
        context: .
        args:
          - NODE_ENV_docker=development
    environment:
      - NODE_ENV_docker=development

    env_file:
      - ./.env  

